name: Build and Push Image to Snowflake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Snowflake Image Registry
        run: |
          echo "${{ secrets.SNOWFLAKE_PASSWORD }}" | docker login \
            ${{ secrets.SNOWFLAKE_REGISTRY_HOST }} \
            -u ${{ secrets.SNOWFLAKE_USERNAME }} \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build -t convert-api:dev src/convert-api

      - name: Tag Docker image
        run: |
          docker tag convert-api:dev \
            ${{ secrets.SNOWFLAKE_REGISTRY_HOST }}/CONTAINER_DEMO_DB/PUBLIC/CONTAINER_REPO/convert-api:dev

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.SNOWFLAKE_REGISTRY_HOST }}/CONTAINER_DEMO_DB/PUBLIC/CONTAINER_REPO/convert-api:dev
